//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ucaktakip {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ucaktakip.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sefer Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yakıt benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bakım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Tipi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yolcu Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uçak Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kalkış-Varış Noktası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kalkış Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Varış Saati benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sefer İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yolcu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s28 {
            get {
                return ResourceManager.GetString("s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s29 {
            get {
                return ResourceManager.GetString("s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Ekle-Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s30 {
            get {
                return ResourceManager.GetString("s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s31 {
            get {
                return ResourceManager.GetString("s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğum Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s32 {
            get {
                return ResourceManager.GetString("s32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cinsiyet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s33 {
            get {
                return ResourceManager.GetString("s33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s34 {
            get {
                return ResourceManager.GetString("s34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yolcu Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s35 {
            get {
                return ResourceManager.GetString("s35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardımcı Pilot: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s36 {
            get {
                return ResourceManager.GetString("s36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kabin Memuru: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s37 {
            get {
                return ResourceManager.GetString("s37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rötar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s38 {
            get {
                return ResourceManager.GetString("s38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Çok Sefere Çıkan Pilot benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s39 {
            get {
                return ResourceManager.GetString("s39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelir-Gider Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Çok Rötar Yapan Uçak Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s40 {
            get {
                return ResourceManager.GetString("s40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gider Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gider benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kazanç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
    }
}
